# Generated by Django 4.2.1 on 2023-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='media/images/')),
                ('number_of_cards', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
